image: jekyll/jekyll:4.2.0

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

test:
  stage: test
  script:
    - jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master

