version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sshocer
    ports:
      - '4000:4000'
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle